/* bafe/codegen.c - emit real C99 source code for a BAFE graph
 *
 * Strategy:
 *   1. Topologically sort the graph
 *   2. For each non-input/constant node, emit:
 *        - a local buffer declaration (if the result is materialized)
 *        - the kernel code that computes the result
 *   3. Emit a copy from the final output buffer to the output pointer
 *
 * For fused ops, we skip the intermediate materialization and emit a
 * single loop nest that computes the result directly.
 *
 * The emitted code targets C99 + OpenMP optional. Phase 1 does not use
 * OpenMP; Phase 2 will.
 */
#include "bafe/codegen.h"
#include "bafe/ops.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

#define MATMUL_TILE 32

/* append a formatted string to a buffer, with bounds checking */
static int _append(char *buf, size_t buf_size, size_t *pos, const char *fmt, ...) {
    if (*pos >= buf_size) return 0;
    va_list ap; va_start(ap, fmt);
    int n = vsnprintf(buf + *pos, buf_size - *pos, fmt, ap);
    va_end(ap);
    if (n < 0) return 0;
    if (*pos + (size_t)n > buf_size) {
        *pos = buf_size;
        return n;
    }
    *pos += (size_t)n;
    return n;
}

/* compute stride for row-major layout */
static int _stride(const bafe_shape *s, int dim) {
    /* stride of dim `dim` in row-major */
    int stride = 1;
    for (int i = s->rank - 1; i > dim; i--) stride *= s->dims[i];
    return stride;
}

/* emit a unique local var name for a node.
 * For input nodes, returns the parameter name (e.g. "A_ptr").
 * For other nodes, returns "v<id>". */
static int _var_name(char *buf, size_t buf_size, const bafe_graph *g, bafe_node_id id) {
    if (id < 0 || id >= g->n_nodes) return snprintf(buf, buf_size, "v_invalid");
    const bafe_node *n = &g->nodes[id];
    if (n->is_input) {
        return snprintf(buf, buf_size, "%s_ptr", n->input_name);
    }
    if (n->is_constant) {
        return snprintf(buf, buf_size, "c%d", id);
    }
    return snprintf(buf, buf_size, "v%d", id);
}

/* emit shape declaration helper */
static int _emit_shape_decl(char *buf, size_t buf_size, size_t *pos,
                            const char *name, const bafe_shape *s) {
    int n = 0;
    n += _append(buf, buf_size, pos, "    /* %s : ", name);
    char sh[64]; bafe_shape_snprintf(sh, sizeof(sh), s);
    n += _append(buf, buf_size, pos, "%s */\n", sh);
    return n;
}

/* emit nested loops for an elementwise op over the output shape */
static int _emit_elementwise_loops(char *buf, size_t buf_size, size_t *pos,
                                    const bafe_shape *out_s,
                                    const char *body_indent) {
    int n = 0;
    char indent[64] = "";
    size_t ind_pos = 0;
    for (int i = 0; i < out_s->rank; i++) {
        n += _append(buf, buf_size, pos, "%sfor (int i%d = 0; i%d < %d; i%d++) {\n",
                     indent, i, i, out_s->dims[i], i);
        ind_pos += strlen("    ");
        if (ind_pos < sizeof(indent)) {
            memset(indent, ' ', ind_pos);
            indent[ind_pos] = '\0';
        }
    }
    n += _append(buf, buf_size, pos, "%s%s", body_indent, "");
    /* now close the loops */
    ind_pos = 0;
    char close_indent[64] = "";
    for (int i = out_s->rank - 1; i >= 0; i--) {
        if (out_s->rank - 1 - i > 0) {
            size_t clen = (size_t)(out_s->rank - 1 - i) * 4;
            if (clen < sizeof(close_indent)) {
                memset(close_indent, ' ', clen);
                close_indent[clen] = '\0';
            }
        }
        n += _append(buf, buf_size, pos, "%s}\n", close_indent);
    }
    return n;
}

/* compute the flat row-major index for a shape given loop variables i0,i1,... */
static int _flat_index(char *buf, size_t buf_size, const bafe_shape *s) {
    /* produces a string like "i0 * D1 * D2 + i1 * D2 + i2" */
    size_t pos = 0;
    if (s->rank == 0) { return snprintf(buf, buf_size, "0"); }
    if (s->rank == 1) { return snprintf(buf, buf_size, "i0"); }
    for (int i = 0; i < s->rank; i++) {
        if (i > 0) pos += (size_t)snprintf(buf + pos, buf_size - pos, " + ");
        pos += (size_t)snprintf(buf + pos, buf_size - pos, "i%d", i);
        for (int j = i + 1; j < s->rank; j++) {
            pos += (size_t)snprintf(buf + pos, buf_size - pos, " * %d", s->dims[j]);
        }
    }
    return (int)pos;
}

/* emit input parameter list */
int bafe_codegen_emit(const bafe_graph *g, const char *kernel_name,
                      char *out, size_t out_size) {
    size_t pos = 0;
    /* header */
    _append(out, out_size, &pos, "/* Auto-generated by BAFE codegen. */\n");
    _append(out, out_size, &pos, "#include <stdint.h>\n");
    _append(out, out_size, &pos, "#include <math.h>\n");
    _append(out, out_size, &pos, "#include <string.h>\n\n");

    /* function signature: void name(const float* A, const float* B, ..., float* out) */
    _append(out, out_size, &pos, "void %s(", kernel_name);
    for (int i = 0; i < g->n_inputs; i++) {
        const bafe_node *in = &g->nodes[g->inputs[i]];
        const char *ctype = bafe_dtype_c_name(in->dtype);
        _append(out, out_size, &pos, "%sconst %s *%s_ptr",
                i == 0 ? "" : ", ", ctype, in->input_name);
    }
    if (g->n_inputs == 0) {
        _append(out, out_size, &pos, "void");
    }
    _append(out, out_size, &pos, ", %s *out_ptr)\n",
            bafe_dtype_c_name(g->nodes[g->outputs[0]].dtype));
    _append(out, out_size, &pos, "{\n");

    /* emit per-input shape constants so we can use them in indexing */
    for (int i = 0; i < g->n_inputs; i++) {
        const bafe_node *in = &g->nodes[g->inputs[i]];
        for (int d = 0; d < in->shape.rank; d++) {
            _append(out, out_size, &pos, "    const int %s_dim%d = %d;\n",
                    in->input_name, d, in->shape.dims[d]);
        }
    }

    /* topo order */
    bafe_node_id order[BAFE_MAX_NODES];
    int n_order = bafe_graph_topo_order((bafe_graph *)g, order, BAFE_MAX_NODES);

    /* emit each node */
    for (int idx = 0; idx < n_order; idx++) {
        bafe_node_id nid = order[idx];
        const bafe_node *n = &g->nodes[nid];
        if (n->is_input || n->is_constant) continue;

        char vname[32]; _var_name(vname, sizeof(vname), g, nid);
        _emit_shape_decl(out, out_size, &pos, vname, &n->shape);

        /* allocate a local buffer for the result */
        size_t numel = bafe_shape_numel(&n->shape);
        const char *ctype = bafe_dtype_c_name(n->dtype);
        _append(out, out_size, &pos, "    %s %s[%zu];\n", ctype, vname, numel);

        /* emit computation */
        if (strcmp(n->op_name, "matmul") == 0) {
            const bafe_node *a = &g->nodes[n->children[0]];
            const bafe_node *b = &g->nodes[n->children[1]];
            int M = n->shape.dims[0];
            int N = n->shape.dims[1];
            int K = a->shape.dims[1];
            char a_name[32]; _var_name(a_name, sizeof(a_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            /* Phase 2: layout-aware index expressions.
             * A is (M, K): row-major -> A[i*K + k] (k contiguous, good)
             *              col-major -> A[i + k*M] (i contiguous, bad for this loop order)
             * B is (K, N): row-major -> B[k*N + j] (j contiguous)
             *              col-major -> B[k + j*K] (k contiguous, GOOD for this loop order)
             * Output (M, N): row-major -> out[i*N + j]
             */
            const char *a_idx = (a->layout == BAFE_LAYOUT_COL_MAJOR)
                ? "%s[i + %d * k]"   /* col-major: A[i + M*k] */
                : "%s[i * %d + k]";  /* row-major: A[i*K + k] */
            const char *b_idx = (b->layout == BAFE_LAYOUT_COL_MAJOR)
                ? "%s[%d * j + k]"   /* col-major: B[k + K*j] -- k contiguous! */
                : "%s[k * %d + j]";  /* row-major: B[k*N + j] */
            int a_stride = (a->layout == BAFE_LAYOUT_COL_MAJOR) ? M : K;
            int b_stride = (b->layout == BAFE_LAYOUT_COL_MAJOR) ? K : N;
            (void)b_stride;
            /* zero output */
            _append(out, out_size, &pos, "    for (int i = 0; i < %d*%d; i++) %s[i] = 0;\n", M, N, vname);
            _append(out, out_size, &pos,
                "    /* matmul: A layout=%s, B layout=%s */\n",
                bafe_layout_name(a->layout), bafe_layout_name(b->layout));
            /* tiled matmul with layout-aware access */
            _append(out, out_size, &pos,
                "    for (int ii = 0; ii < %d; ii += %d) {\n"
                "      for (int jj = 0; jj < %d; jj += %d) {\n"
                "        for (int kk = 0; kk < %d; kk += %d) {\n"
                "          for (int i = ii; i < ii + %d && i < %d; i++) {\n"
                "            for (int j = jj; j < jj + %d && j < %d; j++) {\n"
                "              float acc = 0.0f;\n"
                "              for (int k = kk; k < kk + %d && k < %d; k++) {\n",
                M, MATMUL_TILE, N, MATMUL_TILE, K, MATMUL_TILE,
                MATMUL_TILE, M, MATMUL_TILE, N,
                MATMUL_TILE, K);
            /* emit the access expression with layout-aware strides */
            char a_expr[128], b_expr[128];
            snprintf(a_expr, sizeof(a_expr), a_idx, a_name, a_stride);
            snprintf(b_expr, sizeof(b_expr), b_idx, b_name, b_stride);
            _append(out, out_size, &pos,
                "                acc += %s * %s;\n"
                "              }\n"
                "              %s[i * %d + j] += acc;\n"
                "            }\n"
                "          }\n"
                "        }\n"
                "      }\n"
                "    }\n",
                a_expr, b_expr, vname, N, vname);
        } else if (strcmp(n->op_name, "add") == 0 || strcmp(n->op_name, "sub") == 0 ||
                   strcmp(n->op_name, "mul") == 0) {
            char a_name[32]; _var_name(a_name, sizeof(a_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            char op = strcmp(n->op_name, "add") == 0 ? '+' :
                      strcmp(n->op_name, "sub") == 0 ? '-' : '*';
            _append(out, out_size, &pos, "    for (int i = 0; i < %zu; i++) %s[i] = %s[i] %c %s[i];\n",
                    numel, vname, a_name, op, b_name);
        } else if (strcmp(n->op_name, "bias_add") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            int M = n->shape.dims[0];
            int N = n->shape.dims[1];
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %d; i++) {\n"
                "      for (int j = 0; j < %d; j++) {\n"
                "        %s[i * %d + j] = %s[i * %d + j] + %s[j];\n"
                "      }\n"
                "    }\n", M, N, vname, N, x_name, N, b_name);
        } else if (strcmp(n->op_name, "relu") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %zu; i++) {\n"
                "      %s v = %s[i];\n"
                "      %s[i] = v > 0 ? v : 0;\n"
                "    }\n", numel, ctype, x_name, vname);
        } else if (strcmp(n->op_name, "sigmoid") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %zu; i++) {\n"
                "      %s[i] = 1.0f / (1.0f + expf(-%s[i]));\n"
                "    }\n", numel, vname, x_name);
        } else if (strcmp(n->op_name, "tanh") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %zu; i++) {\n"
                "      %s[i] = tanhf(%s[i]);\n"
                "    }\n", numel, vname, x_name);
        } else if (strcmp(n->op_name, "neg") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            _append(out, out_size, &pos, "    for (int i = 0; i < %zu; i++) %s[i] = -%s[i];\n", numel, vname, x_name);
        } else if (strcmp(n->op_name, "transpose") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            /* for rank-2 transpose */
            if (n->shape.rank == 2) {
                int M = n->shape.dims[0], N = n->shape.dims[1];
                _append(out, out_size, &pos,
                    "    for (int i = 0; i < %d; i++)\n"
                    "      for (int j = 0; j < %d; j++)\n"
                    "        %s[i * %d + j] = %s[j * %d + i];\n",
                    M, N, vname, N, x_name, M);
            } else {
                _append(out, out_size, &pos, "    /* transpose rank %d not supported, fallback to memcpy */\n", n->shape.rank);
                _append(out, out_size, &pos, "    memcpy(%s, %s, %zu);\n", vname, x_name, numel * bafe_dtype_byte_size(n->dtype));
            }
        } else if (strcmp(n->op_name, "reduce_sum") == 0 || strcmp(n->op_name, "reduce_max") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            /* simple: reduce over last axis, keepdims=false */
            if (n->attrs.n_axes == 1 && n->shape.rank == 1) {
                int N = g->nodes[n->children[0]].shape.dims[0];
                if (strcmp(n->op_name, "reduce_sum") == 0) {
                    _append(out, out_size, &pos, "    %s[0] = 0;\n    for (int i = 0; i < %d; i++) %s[0] += %s[i];\n",
                            vname, N, vname, x_name);
                } else {
                    _append(out, out_size, &pos, "    %s[0] = %s[0];\n    for (int i = 1; i < %d; i++) if (%s[i] > %s[0]) %s[0] = %s[i];\n",
                            vname, x_name, N, x_name, vname, vname, x_name);
                }
            } else {
                _append(out, out_size, &pos, "    /* reduce with axes/keepdims not implemented, zero fill */\n");
                _append(out, out_size, &pos, "    for (int i = 0; i < %zu; i++) %s[i] = 0;\n", numel, vname);
            }
        } else if (strcmp(n->op_name, "reshape") == 0 ||
                   strcmp(n->op_name, "broadcast_to") == 0 ||
                   bafe_op_is_layout_transform(n->op_name)) {
            /* Phase 2: layout_transform is a metadata change at the IR level,
             * but at the C level we materialize it as a memcpy. The cost model
             * penalizes this, so the optimizer prefers to eliminate redundant
             * transforms via the layout rewrite rules. */
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            if (bafe_op_is_layout_transform(n->op_name)) {
                _append(out, out_size, &pos, "    /* layout_transform to %s (data copy) */\n",
                        n->attrs.name[0] ? n->attrs.name : "(default)");
            }
            _append(out, out_size, &pos, "    memcpy(%s, %s, %zu);\n", vname, x_name,
                    numel * bafe_dtype_byte_size(n->dtype));
        } else if (strcmp(n->op_name, "fused_matmul_relu") == 0) {
            const bafe_node *a = &g->nodes[n->children[0]];
            int M = n->shape.dims[0], N = n->shape.dims[1], K = a->shape.dims[1];
            const bafe_node *b_unused = &g->nodes[n->children[1]]; (void)b_unused;
            char a_name[32]; _var_name(a_name, sizeof(a_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %d; i++)\n"
                "      for (int j = 0; j < %d; j++) {\n"
                "        float acc = 0.0f;\n"
                "        for (int k = 0; k < %d; k++)\n"
                "          acc += %s[i * %d + k] * %s[k * %d + j];\n"
                "        %s[i * %d + j] = acc > 0 ? acc : 0;\n"
                "      }\n",
                M, N, K, a_name, K, b_name, N, vname, N);
        } else if (strcmp(n->op_name, "fused_matmul_bias") == 0) {
            const bafe_node *a = &g->nodes[n->children[0]];
            int M = n->shape.dims[0], N = n->shape.dims[1], K = a->shape.dims[1];
            const bafe_node *b_unused = &g->nodes[n->children[1]]; (void)b_unused;
            char a_name[32]; _var_name(a_name, sizeof(a_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            char bias_name[32]; _var_name(bias_name, sizeof(bias_name), g, n->children[2]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %d; i++)\n"
                "      for (int j = 0; j < %d; j++) {\n"
                "        float acc = 0.0f;\n"
                "        for (int k = 0; k < %d; k++)\n"
                "          acc += %s[i * %d + k] * %s[k * %d + j];\n"
                "        %s[i * %d + j] = acc + %s[j];\n"
                "      }\n",
                M, N, K, a_name, K, b_name, N, vname, N, bias_name);
        } else if (strcmp(n->op_name, "fused_matmul_bias_relu") == 0) {
            const bafe_node *a = &g->nodes[n->children[0]];
            int M = n->shape.dims[0], N = n->shape.dims[1], K = a->shape.dims[1];
            const bafe_node *b_unused = &g->nodes[n->children[1]]; (void)b_unused;
            char a_name[32]; _var_name(a_name, sizeof(a_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            char bias_name[32]; _var_name(bias_name, sizeof(bias_name), g, n->children[2]);
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %d; i++)\n"
                "      for (int j = 0; j < %d; j++) {\n"
                "        float acc = 0.0f;\n"
                "        for (int k = 0; k < %d; k++)\n"
                "          acc += %s[i * %d + k] * %s[k * %d + j];\n"
                "        acc += %s[j];\n"
                "        %s[i * %d + j] = acc > 0 ? acc : 0;\n"
                "      }\n",
                M, N, K, a_name, K, b_name, N, bias_name, vname, N);
        } else if (strcmp(n->op_name, "fused_bias_relu") == 0) {
            char x_name[32]; _var_name(x_name, sizeof(x_name), g, n->children[0]);
            char b_name[32]; _var_name(b_name, sizeof(b_name), g, n->children[1]);
            int M = n->shape.dims[0], N = n->shape.dims[1];
            _append(out, out_size, &pos,
                "    for (int i = 0; i < %d; i++)\n"
                "      for (int j = 0; j < %d; j++) {\n"
                "        float v = %s[i * %d + j] + %s[j];\n"
                "        %s[i * %d + j] = v > 0 ? v : 0;\n"
                "      }\n",
                M, N, x_name, N, b_name, vname, N);
        } else {
            _append(out, out_size, &pos, "    /* unsupported op %s, zero fill */\n", n->op_name);
            _append(out, out_size, &pos, "    for (int i = 0; i < %zu; i++) %s[i] = 0;\n", numel, vname);
        }
    }

    /* copy final output to out_ptr */
    bafe_node_id out_id = g->outputs[0];
    const bafe_node *out_node = &g->nodes[out_id];
    char out_vname[32]; _var_name(out_vname, sizeof(out_vname), g, out_id);
    size_t out_numel = bafe_shape_numel(&out_node->shape);
    _append(out, out_size, &pos, "    memcpy(out_ptr, %s, %zu * sizeof(%s));\n",
            out_vname, out_numel, bafe_dtype_c_name(out_node->dtype));
    _append(out, out_size, &pos, "}\n");

    return (int)pos;
}

char *bafe_codegen_emit_alloc(const bafe_graph *g, const char *kernel_name) {
    /* estimate size: ~512 bytes per node + 4KB overhead */
    size_t size = 4096 + 1024 * (size_t)g->n_nodes;
    char *buf = malloc(size);
    if (!buf) return NULL;
    int n = bafe_codegen_emit(g, kernel_name, buf, size);
    if (n < 0) { free(buf); return NULL; }
    return buf;
}
