#!/usr/bin/env python3
"""Open GitHub issues for BAFE Phase 2/3 work."""
import json
import os
import urllib.request
import urllib.error

REPO = "AVmakeralt/BAFE-basic-algibra-fusion-engine-"
TOKEN = "REDACTED"

ISSUES = [
    {
        "title": "[Phase 2] Stochastic search layer for non-obvious rewrites",
        "body": """## Goal

Add a stochastic exploration layer on top of the deterministic rewrite engine, as described in the design doc:

> stochastic layer
>   - explores crazy rewrites
>   - discovers non-obvious transformations

## Design

The current `bafe_rewrite_find()` does a single forward pass with deterministic rules. We need:

1. **A stochastic rewriter** that randomly applies rewrites from a weighted distribution
2. **A population of alternative graphs** generated by N stochastic passes
3. **A budget controller** that limits search by time / node count / iteration count
4. **Integration with the e-graph** — stochastic results get unioned in just like deterministic ones

## API sketch

```c
typedef struct {
    int max_iters;
    int max_nodes;
    int max_rewrites;
    double temperature;       /* simulated annealing */
    unsigned int seed;
} bafe_search_budget;

int bafe_rewrite_stochastic(const bafe_graph *g, bafe_alt_list *out,
                            const bafe_search_budget *budget);
```

## Acceptance criteria

- [ ] `bafe_rewrite_stochastic()` produces alternatives that deterministic mode misses
- [ ] Time budget is respected (search terminates within `max_iters * estimated_iter_time`)
- [ ] Results feed into the existing e-graph + extractor pipeline
- [ ] Tests demonstrate finding a non-obvious rewrite on a small graph

## References

- Design doc: "stochastic + e-graph fits" section
- Related: egg's `BackoffScheduler` for inspiration
"""
    },
    {
        "title": "[Phase 2] Layout superoptimizer (row/col/blocked/tensor-core)",
        "body": """## Goal

Add a first-class layout search engine that co-optimizes with algebra and scheduling.

## Design

From the design discussion:

> a "mini superoptimizer for memory layouts" is exactly the correct decomposition.
>
> It explores:
>   1. Layout formats (NCHW / NHWC / blocked / tensor-core)
>   2. Memory ordering (row-major vs col-major, hierarchical tiling)
>   3. Layout fusion compatibility (which ops can share layout)
>   4. Re-layout strategy placement (when to transform, when to keep stable)

## Implementation plan

1. **Extend `bafe_layout` enum** — already defined in `types.h` but currently only ROW_MAJOR is used in codegen
2. **Add layout annotations to IR nodes** — a `bafe_layout` field on `bafe_node`
3. **Add layout rewrite rules** — e.g., `matmul(A, B)` with A row-major + B col-major is faster than the reverse
4. **Add layout cost to the cost model** — penalize layout conversions, reward layout-compatible fusion
5. **Extend codegen** — emit col-major access patterns, blocked tiling for matmul
6. **Phase 3: GPU tensor-core layout** — emit SPIR-V layouts matching tensor core alignment

## API sketch

```c
/* add a layout tag to a node */
bafe_node_id bafe_graph_add_input_with_layout(bafe_graph *g, const char *name,
                                              const bafe_shape *shape,
                                              bafe_dtype dtype,
                                              bafe_layout layout);

/* layout rewrite rule */
typedef struct {
    const char *name;
    bool (*applies)(const bafe_graph *g, const bafe_node *n);
    bafe_alternative (*rewrite)(const bafe_graph *g, const bafe_node *n);
    bafe_layout target_layout;
} bafe_layout_rule;
```

## Acceptance criteria

- [ ] IR nodes carry a layout annotation
- [ ] Cost model rewards layout-compatible fusion
- [ ] Codegen emits col-major access when beneficial
- [ ] Benchmark: matmul with row-major vs col-major inputs shows measurable speed difference
- [ ] Tests cover layout propagation through add/mul/relu
"""
    },
    {
        "title": "[Phase 2] GPU backend via Vulkan compute / SPIR-V",
        "body": """## Goal

Add a Vulkan/SPIR-V backend so BAFE can emit GPU kernels, not just CPU C.

## Design

From the design doc:

> ### GPU path (Vulkan compute / SPIR-V)
> You translate kernel plan into:
>   * workgroup layout
>   * memory bindings
>   * SPIR-V compute shader
>
> Important: this is NOT general compilation. It is **template-driven synthesis**.

## Implementation plan

1. **SPIR-V emitter** — generate SPIR-V bytecode directly (no GLSL/HLSL front-end)
2. **Workgroup sizing** — auto-tile based on output shape and hardware limits
3. **Memory bindings** — map input tensors to descriptor set slots
4. **Vulkan dispatch** — manage a Vulkan device, command buffer, submission
5. **Code path selection** — `bafe_jit_get_or_compile()` chooses CPU or GPU based on graph + target

## API sketch

```c
typedef enum {
    BAFE_TARGET_CPU,
    BAFE_TARGET_VULKAN,
} bafe_target;

bafe_kernel_fn bafe_jit_get_or_compile_for(const bafe_graph *g,
                                            bafe_target target,
                                            char *err_buf, size_t err_buf_size);
```

## Acceptance criteria

- [ ] A `matmul` graph compiles to a working Vulkan compute shader
- [ ] The shader produces correct numerical output (matches numpy)
- [ ] Dispatch overhead is < 1ms (so small matmuls aren't dominated by launch cost)
- [ ] CPU vs GPU selection works automatically based on shape heuristics

## Dependencies

- Vulkan headers (`vulkan.h`)
- A Vulkan loader (`libvulkan.so`)
- Optional: validation layers for debugging
"""
    },
    {
        "title": "[Phase 2] Multi-tier pruning with time budget",
        "body": """## Goal

Add a resource-bounded search controller that prevents combinatorial explosion.

## Design

From the design discussion:

> You are not building "pruning." You are building:
> > a resource-bounded search controller for program synthesis

Multi-tier pruning:

| Level | What it does | Cost |
|-------|--------------|------|
| A | Hard structural pruning (invalid shapes, illegal fusion) | O(1)-O(n) |
| B | Heuristic scoring (compute + memory + fusion potential) | cheap |
| C | Beam search (keep top-k candidates, k grows with budget) | medium |
| D | Stochastic survival (softmax over cost with temperature) | depends |

Time-budget regimes:

| time | behavior |
|------|----------|
| 1 ms | greedy only |
| 10 ms | light stochastic |
| 100 ms | e-graph + beam search |
| 1000 ms+ | deep exploration + layout search |

## API sketch

```c
typedef struct {
    double total_time_ms;
    int expansion_budget;
    int rewrite_budget;
    int depth_budget;
    double initial_temperature;
} bafe_budget;

/* Run optimization with a budget. Returns the best plan found
 * within the time limit (anytime optimization). */
int bafe_optimize_with_budget(const bafe_graph *input, bafe_graph *optimized,
                              const bafe_budget *budget,
                              char *err_buf, size_t err_size);
```

## Acceptance criteria

- [ ] `bafe_optimize_with_budget()` with 1ms budget returns the greedy result
- [ ] With 100ms budget, it explores the e-graph
- [ ] With 1000ms budget, it runs stochastic + layout search
- [ ] Anytime property: if interrupted, returns the best-so-far
- [ ] Kill switches: max_nodes, max_rewrites, max_egraph_size all enforced

## Depends on

- #1 (stochastic search)
- #2 (layout superoptimizer)
"""
    },
    {
        "title": "[Phase 2] Learned cost model with feedback loop",
        "body": """## Goal

Replace the hand-tuned cost model with a learned one that improves over time based on observed kernel runtimes.

## Design

From the design discussion:

> ## 4. Observed cost (feedback correction layer)
> After executing kernels, you measure:
>   * actual runtime
>   * actual memory throughput
>   * cache misses
>   * GPU occupancy
> Then: `error = observed_cost - predicted_cost`
> And you feed it back into the model.

## Implementation plan

1. **Log training data** — for every JIT-compiled kernel, record (graph features, predicted cost, actual runtime)
2. **Feature extractor** — per-node features: op type, shape, dtype, layout, child count, fusion depth
3. **Model** — start simple (linear regression on log-features), graduate to a small MLP later
4. **Calibration loop** — periodically refit the model on the accumulated log
5. **Cost model interface** — `bafe_cost_model` already exists; add a `bafe_cost_model_learned` variant

## API sketch

```c
typedef struct {
    /* feature vector for a single node */
    double features[32];
    int n_features;
    double predicted_cost;
    double observed_cost;   /* filled in after execution */
} bafe_cost_record;

/* Log a cost record (called by the JIT after execution). */
void bafe_cost_log(const bafe_cost_record *rec);

/* Refit the learned model on all logged records. */
int bafe_cost_model_refit(bafe_cost_model *m);
```

## Acceptance criteria

- [ ] Cost records are logged to disk (SQLite or JSONL)
- [ ] A simple linear model can be trained on the log
- [ ] After refitting, predictions correlate with observations (R^2 > 0.5)
- [ ] The extractor uses the learned model when available, falls back to hand-tuned otherwise
- [ ] Tests show that the learned model picks a different (better) kernel after enough samples
"""
    },
    {
        "title": "[Phase 3] Auto-tuning loop with profiling feedback",
        "body": """## Goal

Close the loop: compile a kernel, profile it, and re-optimize based on actual measurements.

## Design

This builds on top of the learned cost model (#5). The flow:

```
user calls f(A, B)
   |
   v
optimize + compile + run (with timing)
   |
   v
log: (graph, kernel, runtime)
   |
   v
if accumulated enough samples:
   refit cost model
   invalidate JIT cache for affected graphs
   re-optimize on next call
```

## API sketch

```c
typedef struct {
    bool enable_profiling;
    int refit_threshold;       /* refit after N samples */
    double invalidation_ratio; /* invalidate cache if predictions drift > X% */
} bafe_autotune_config;

void bafe_autotune_configure(const bafe_autotune_config *cfg);
```

## Acceptance criteria

- [ ] Profiling overhead < 5% of kernel runtime
- [ ] After N=20 calls to the same graph shape, the cost model is refit
- [ ] If refit produces a different best kernel, the old .so is invalidated
- [ ] Benchmark: a workload with mixed shapes shows speedup over time as the model learns
- [ ] The auto-tuner never makes things worse (best-so-far is always kept)

## Depends on

- #5 (learned cost model)
"""
    },
    {
        "title": "[Phase 3] Multi-kernel fusion across call boundaries",
        "body": """## Goal

When a user calls `f(A, B)` then `g(C, D)` in sequence, BAFE should be able to fuse them into a single kernel if it's beneficial.

## Design

This is the most ambitious Phase 3 feature. It requires:

1. **Call graph tracking** — record sequences of JIT'd calls
2. **Cross-kernel dataflow** — detect when one kernel's output feeds the next
3. **Fusion candidate generation** — propose fused IR graphs spanning multiple original kernels
4. **Cache invalidation** — when a fused version is compiled, the individual kernels are no longer needed
5. **Fallback** — if the fused version is slower (e.g., due to register pressure), revert

## API sketch

```python
import bafe

@bafe.jit
def f(A, B):
    return bafe.matmul(A, B)

@bafe.jit
def g(C):
    return bafe.relu(C)

# After enough calls, BAFE notices that f's output always feeds g,
# and compiles a fused version:
A = np.random.randn(64, 64).astype(np.float32)
B = np.random.randn(64, 64).astype(np.float32)
out = g(f(A, B))   # calls the fused kernel automatically
```

## Acceptance criteria

- [ ] Call patterns are logged (which graphs feed which)
- [ ] After N occurrences of a pattern, a fused candidate is compiled
- [ ] The fused candidate is benchmarked against the unfused sequence
- [ ] If faster, the fused version is used for subsequent matches
- [ ] If slower, the unfused version is kept and the pattern is blacklisted

## Depends on

- #5 (learned cost model, for the comparison)
- #6 (auto-tuning loop, for the profiling infrastructure)
"""
    },
    {
        "title": "[Phase 3] SMT sanity proofs (optional verification layer)",
        "body": """## Goal

Add an optional SMT-based verification step that proves rewrite rules preserve semantics.

## Design

From the design doc:

> ### Only later:
> * SMT proofs (optional sanity layer, not core)

This is explicitly *not* required for the system to work — it's a safety net for catching bugs in rewrite rules.

## Implementation plan

1. **Symbolic executor** — given an IR graph, produce an SMT formula encoding its semantics
2. **Rule verifier** — for each rewrite rule, prove that the original and rewritten graphs produce equal outputs for all valid inputs
3. **Z3 integration** — use Z3 as the SMT solver (via its C API)
4. **CI check** — run the verifier on all rules as part of the test suite

## API sketch

```c
/* Verify that a rewrite rule preserves semantics.
 * Returns 0 if verified, non-zero if a counterexample is found
 * (counterexample is written to out_inputs in that case). */
int bafe_verify_rule(const bafe_rule *rule,
                     bafe_shape *out_counterexample,
                     char *err_buf, size_t err_size);
```

## Acceptance criteria

- [ ] All 13 existing Phase 1 rules pass verification
- [ ] A deliberately-broken rule (e.g., `add(a, b) -> sub(a, b)`) is caught
- [ ] Verification runs in < 10 seconds per rule
- [ ] CI runs the verifier on every PR

## Notes

- This is research-grade. Z3's SMT solving for tensor algebra is an open problem.
- We may need to limit the verifier to small shapes (e.g., 4x4) and trust that the rules generalize.
"""
    },
]


def open_issue(issue):
    url = f"https://api.github.com/repos/{REPO}/issues"
    data = json.dumps(issue).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        method="POST",
        headers={
            "Authorization": f"Bearer {TOKEN}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req) as r:
            resp = json.loads(r.read())
            return resp.get("number"), resp.get("html_url")
    except urllib.error.HTTPError as e:
        return None, f"HTTP {e.code}: {e.read().decode()[:200]}"


def main():
    for issue in ISSUES:
        num, url = open_issue(issue)
        print(f"  #{num}: {issue['title']}")
        print(f"    {url}")
        print()


if __name__ == "__main__":
    main()
